mod e01_if_else;
mod e02_loops;
mod e03_const;
mod e04_mutability;
mod e05_shadowing;
mod e06_scalar_types;
mod e07_numeric_operations;
mod e08_tuple;
mod e09_array;
mod e10_string;
mod e11_hash_map;
mod e12_functions;
mod e13_ownership;
mod e14_slice;
mod e15_struct;
mod e16_enum;
mod e17_match;
mod e18_crate;
mod e19_module;
mod e20_use;
mod e21_test;
mod e22_trait;
mod e23_static_lifetime;
mod e24_generics;
mod e25_lifetime;

fn main() {
    e01_if_else::test();
    e02_loops::test();
    e03_const::test();
    e04_mutability::test();
    e05_shadowing::test();
    e06_scalar_types::test();
    e07_numeric_operations::test();
    e08_tuple::test();
    e09_array::test();
    e10_string::test();
    e11_hash_map::test();
    e12_functions::test();
    e13_ownership::test();
    e14_slice::test();
    e15_struct::test();
    e16_enum::test();
    e17_match::test();
    e18_crate::test();
    e19_module::test();
    e20_use::test();
    e21_test::test();
    e22_trait::test();
    e23_static_lifetime::test();
    e24_generics::test();
    e25_lifetime::test();
}
